const satWordsWithDefinitions = {
    "abate": "to reduce in intensity",
    "abide": "to accept or act in accordance with",
    "adapt": "to adjust or modify to suit conditions",
    "adept": "highly skilled or proficient",
    "adore": "to love deeply and respect",
    "aisle": "a passage between rows of seats",
    "alarm": "a sudden fear or distressing suspense",
    "amend": "to make changes to improve",
    "amuse": "to entertain or occupy in a pleasing manner",
    "angle": "the space between two intersecting lines",
    "asset": "a valuable thing, person, or quality",
    "avoid": "to keep away from or stop oneself from doing",
    "banal": "lacking in originality, obvious, and boring",
    "bland": "lacking strong features or characteristics",
    "bless": "to confer or invoke divine favor upon",
    "brisk": "active and energetic",
    "burly": "large and strong; heavily built",
    "carve": "to cut a hard material to produce an object",
    "cease": "to bring or come to an end",
    "chaos": "complete disorder and confusion",
    "charm": "the power or quality of delighting, attracting",
    "cling": "to hold on tightly to",
    "coast": "the part of the land near the sea",
    "creed": "a set of beliefs or aims",
    "dealt": "past tense of deal; to distribute or apportion",
    "debut": "a person's first appearance or performance",
    "deter": "to discourage from an action",
    "drape": "to arrange cloth loosely over something",
    "elite": "a select group that is superior",
    "enact": "to make into law",
    "enter": "to come or go into",
    "equal": "the same in quantity, size, degree, or value",
    "equip": "to provide with necessary items",
    "error": "a mistake",
    "essay": "a short piece of writing on a particular subject",
    "ethic": "moral principles that govern behavior",
    "event": "an occurrence or happening",
    "exile": "to banish from one's country",
    "exist": "to have objective reality or being",
    "faith": "complete trust or confidence in someone or something",
    "fatal": "causing death",
    "feign": "to pretend to be affected by",
    "ferry": "a boat or ship for conveying passengers and goods",
    "flair": "a special or instinctive aptitude",
    "fleet": "a group of ships sailing together",
    "flora": "the plants of a particular region",
    "foray": "a sudden attack or incursion",
    "forte": "a thing at which someone excels",
    "found": "to establish or originate",
    "fraud": "wrongful deception for financial gain",
    "glean": "to gather bit by bit",
    "grasp": "to seize and hold firmly",
    "haste": "excessive speed or urgency",
    "hasty": "done with excessive speed",
    "hover": "to remain in one place in the air",
    "imbue": "to inspire or permeate with a feeling",
    "inane": "silly or stupid",
    "inbox": "an electronic folder for incoming emails",
    "index": "an alphabetical list of subjects",
    "infer": "to deduce or conclude",
    "inner": "situated inside",
    "intro": "an introduction",
    "jaded": "tired or bored after having too much of something",
    "jolly": "happy and cheerful",
    "kneel": "to go down on one's knee",
    "laden": "heavily loaded or weighed down",
    "lapse": "a temporary failure",
    "latch": "a fastening or lock",
    "lithe": "thin, supple, and graceful",
    "locus": "a particular position or place",
    "mirth": "amusement, especially as expressed in laughter",
    "moist": "slightly wet",
    "nadir": "the lowest point",
    "noble": "having fine personal qualities",
    "novel": "new or unusual in an interesting way",
    "nylon": "a synthetic polymer",
    "obese": "grossly overweight",
    "ogle": "to stare at in a lecherous manner",
    "opine": "to hold and state as one's opinion",
    "ovate": "egg-shaped",
    "overt": "done or shown openly",
    "payer": "a person who pays",
    "peril": "serious and immediate danger",
    "pious": "devoutly religious",
    "prone": "likely to or liable to suffer from",
    "quota": "a fixed share of something",
    "rabid": "having extreme support",
    "raven": "a large black bird",
    "recur": "to occur again periodically",
    "reign": "hold royal office; rule as king or queen",
    "relic": "an object from the past",
    "resin": "a sticky flammable organic substance",
    "rogue": "a dishonest or unprincipled man",
    "rural": "relating to the countryside",
    "savor": "to enjoy completely",
    "sheer": "nothing other than; unmitigated",
    "shirk": "to avoid or neglect",
    "slyly": "in a cunning or deceitful manner",
    "spurn": "to reject with disdain",
    "sworn": "past participle of swear",
    "thwart": "to prevent someone from accomplishing something",
    "tilde": "a symbol used in various languages",
    "tithe": "one tenth of annual produce or earnings",
    "torso": "the trunk of the human body",
    "toxic": "poisonous",
    "trite": "lacking originality",
    "urban": "relating to a city",
    "vague": "uncertain, indefinite, or unclear",
    "vapid": "offering nothing that is stimulating",
    "vista": "a pleasing view",
    "vivid": "producing powerful feelings or strong images",
    "waste": "use or expend carelessly",
    "witty": "showing quick and inventive verbal humor",
    "wrath": "extreme anger",
    "yearn": "to have an intense feeling of longing"
};

export default satWordsWithDefinitions